# Site settings
title: The Arnold and Deanne Kaplan of Early American Judaica
email: judaicadh@gmail.com
description: >
  1550-1890

baseurl: "/kaplan" # the subpath of your site, e.g. /blog/
url: https://judaicadh.github.io # the base hostname & protocol for your site

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
#bootwatch: custom

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
