[build]
command = "npm run build"
publish = ".netlify/output"

[functions]
directory = ".netlify/functions"

[[headers]]
for = "/_astro/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"