const schemaTypeMap: Record<string, string> = {
	'Account Book': 'CreativeWork',
	'Broadside': 'CreativeWork',
	'Albumen Prints': 'Photograph',
	'Almanac': 'PublicationIssue',
	'Archival Collection': 'ArchiveComponent',
	'Archival Materials': 'CreativeWork',
	'Ash Tray': 'VisualArtwork',
	'Baptismal Certificate': 'CreativeWork',
	'Bill of Exchange': 'FinancialProduct',
	'Billhead': 'CreativeWork',
	'Blotter': 'VisualArtwork',
	'Bond': 'FinancialProduct',
	'Book': 'Book',
	'Bookplate': 'CreativeWork',
	'Bottle': 'VisualArtwork',
	'Box': 'VisualArtwork',
	'Brief': 'LegalDocument',
	'Brush': 'CreativeWork',
	'Buckle Discs': 'CreativeWork',
	'Business Cards': 'CreativeWork',
	'Cabinet Photographs': 'Photograph',
	'Calendar': 'CreativeWork',
	'Calling Cards': 'CreativeWork',
	'Card': 'CreativeWork',
	'Cartes-de-visite': 'Photograph',
	'Catalogue': 'CreativeWork',
	'Certificate': 'CreativeWork',
	'Check': 'FinancialProduct',
	'Chromolithograph': 'CreativeWork',
	'Congressional Record': 'GovernmentService',
	'Contract': 'LegalDocument',
	'Currency': 'CreativeWork',
	'Daguerreotypes': 'Photograph',
	'Dance Cards': 'CreativeWork',
	'Deed': 'LegalDocument',
	'Diary': 'CreativeWork',
	'Drawing': 'VisualArtwork',
	'Engraving': 'CreativeWork',
	'Envelope': 'CreativeWork',
	'Ephemera': 'CreativeWork',
	'Etching': 'VisualArtwork',
	'Financial Record': 'CreativeWork',
	'Government Record': 'GovernmentService',
	'Greeting Cards': 'CreativeWork',
	'Invitation': 'CreativeWork',
	'Jug': 'VisualArtwork',
	'Ketubah': 'CreativeWork',
	'Kiddush Cup': 'CreativeWork',
	'Lamp': 'CreativeWork',
	'Ledger': 'CreativeWork',
	'Letter': 'CreativeWork',
	'Lithograph': 'VisualArtwork',
	'Manuscript': 'Manuscript',
	'Map': 'Map',
	'Membership Certificate': 'CreativeWork',
	'Menu': 'CreativeWork',
	'Military Records': 'CreativeWork',
	'Oil Painting': 'VisualArtwork',
	'Pamphlet': 'PublicationIssue',
	'Passport': 'CreativeWork',
	'Periodical': 'PublicationIssue',
	'Photographs': 'Photograph',
	'Poem': 'CreativeWork',
	'Postcard': 'CreativeWork',
	'Poster': 'CreativeWork',
	'Receipt': 'CreativeWork',
	'Sculpture': 'Sculpture',
	'Sheet Music': 'CreativeWork',
	'Trade Card': 'CreativeWork',
	'Watercolor': 'VisualArtwork',
	'Will': 'LegalDocument'
}

// Fallback type for undefined categories
const defaultType = 'CreativeWork'

// Function to get Schema.org type based on category
function getSchemaType(category: string): string {
	return schemaTypeMap[category] || defaultType
}

export { schemaTypeMap, getSchemaType, defaultType }